version: "3.8"

x-common-variables: &common-variables
  environment:
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgres://airflow:airflow@postgres:5432/airflow
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
    - AIRFLOW__CORE__FERNET_KEY=123
    - AIRFLOW__CORE__STORE_SERIALIZED_DAGS=True
    - AIRFLOW__CORE__STORE_DAG_CODE=True

services:
  webserver:
    <<: *common-variables
    image: apache/airflow:1.10.12-python3.8
    depends_on:
      - postgres
    command: webserver
    ports:
      - "80:8080"
    restart: always
    healthcheck:
        test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
        interval: 30s
        timeout: 30s
        retries: 3

  scheduler:
    <<: *common-variables
    image: airflow-custom:1.10.12-python3.8
    build: ./
    depends_on:
      - postgres
    volumes:
        - ./dags:/opt/airflow/dags
        - ./plugins:/opt/airflow/plugins
    command: scheduler
    restart: always

  postgres:
    image: postgres
    environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow
    logging:
        options:
            max-size: 10m
            max-file: "3"
    ports:
      - "5432:5432"
    restart: always
    volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: